version: "3.6"
services:
    nginx_react_test:
        image: nginx:latest
        # ports:
        #     - 8080:80
        volumes:
            - type: bind 
              source: ./conf/default.conf
              target: /etc/nginx/conf.d/default.conf
        network_mode: host